import './globals.css'
import { Inter } from 'next/font/google'
import  Quiz from "../app/components/Quiz"
import MyProvider from './components/MyProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <MyProvider>
         {children}
         {/* <Quiz/> */}
       </MyProvider>
       </body>
      
    </html>
  ) 
}
